[package]
name = "discplot"
version = "0.1.0"
authors = ["ckie <git-525ff67@ckie.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.0"
csv = "1.1.5"
chrono = "0.4.19"
